Fix relative paths in prototypes.h (#1878)
Fix Arduino IDE error by changing to proper relative paths:

```
In file included from sketch\config/all.h:36:0, from C:\Programy\arduino_projekty\espurna_dev\code\espurna\espurna.ino:22:
sketch\config/prototypes.h:178:86: fatal error: static/letsencrypt_isrgroot_pem.h: No such file or directory

#include "static/letsencrypt_isrgroot_pem.h" // Default to LetsEncrypt X3 certificate

compilation terminated.
```